
# PV is efs = elastic file system, we create this in aws cloud 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  # capacity and storage is dummy here, STORAGE IS UNLIMITED, STORAGE GROWS BY USEAGE
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: "" # for static provisioning storage class should be empty 
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: efs:fs-01458611d268e2544 # Replace with your EFS ID

---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

---
# POD
apiVersion: v1
kind: Pod
metadata:
  name: efs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-static