apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    envirnoment: dev
    project: roboshop
    purpose: poc

spec:
  containers:
  - name: nginx
    image: nginx

  - name: almalinux
    image: almalin:9

  