# labels are used to communcation between any resources, like service can select pod by using labels
 # deployment can select pod by using labels  every thing is labels

 # because "LABELS", "RESOURCES" can take with each other

apiVersion: v1
kind: Pod
metadata:
  name: labels-demo # pod name
  labels:
    project: roboshop
    environment: dev
    purpose: poc
spec:
  containers:
  - name: nginx
    image: nginx