apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx

    # environment variables
    env:
    - name: project      # - means data type list -
      value: "roboshop"
    - name: course
      value: "k8"
    - name: duration
      value: "150 hrs"