apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    project: roboshop
    tier: frontend
    component: frontend
spec:
  # modify replicas according to your case
  replicas: 10
  # replicaset uses these labels to match pods
  selector:
    matchLabels:
      project: roboshop
      tier: frontend
      component: frontend
  # pod definition, but doesnt have apivesrion and kind, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx