apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # labels related to deployment resource
  labels:
    project: roboshop
    tier: frontend
    component: frontend
    purpose: deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      project: roboshop
      tier: frontend
      component: frontend
      purpose: deployment
  # Pod
  template:
    metadata:
      labels:
        project: roboshop
        tier: frontend
        component: frontend
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

# deployment will create one REPLICASET, sience replicas: 3, then REPLICASET will create  3 PODS
# pod is subset of replicaset. replicaset is subset of deployment